host: 127.0.0.1
port: 9225
enable_metrics:
  jvm_gc: true
  jvm_memory: true
  jvm_threads: true
  online_players: true
  online_servers: true
  player_connects: true
  logins: true
  player_disconnects: true
  post_logins: true
  pre_logins: true
  pings: true
  redis_joined_players: true
  redis_disconnected_players: true
  redis_online_players: true
  redis_bungee_online_proxies: true